//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace examen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturas
    {
        public int id_Factura { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Cliente_id { get; set; }
        public Nullable<int> Vendedor_id { get; set; }
        public Nullable<double> Iva { get; set; }
        public Nullable<double> Descuento { get; set; }
        public Nullable<int> Detalle_Factura_id { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Detalles_Facturas Detalles_Facturas { get; set; }
        public virtual Vendedores Vendedores { get; set; }
    }
}
